### ISSUE TITLE
Integrate lintr

### ISSUE THREAD

**Issue by hsloot** [hsloot/rmo#2]
### Feature Request: Integrate `lintr`code-checking

The `R`-package [`lintr`](https://github.com/jimhester/lintr) allows to define static code tests to ensure certain code standards and styles are fulfilled. 

### To-Do's:

- [x] Choose coding style
- [x] Create `lintr` setup according to code style
- [x] Use lintr with travis-ci 
- [x] Write section in contributing document
- [x] Update pull request document

**Comment by hsloot** [comment]
choose default style with the following changes: 
```
linters: with_defaults(
    infix_spaces_linter = NULL,
    line_length_linter = line_length_linter(100),
    object_name_linter = object_name_linter("snake_case")
  )
```
