### ISSUE TITLE
Better collaboration instructions

### ISSUE THREAD

**Issue by hsloot** [hsloot/rmo#3]
### Github: Better collaboration

Currently, the guidelines on collaborations for this project are not very specific. 

### To-Do's:

- [x] Create issue template
- [x] Create pull request template
- [x] Create code of conduct
- [x] Create contributing document 
- [x] Create section in `README.Rmd` for contributing

**Comment by hsloot** [comment]
reopened the issue and added new to-do for a section in the readme on contributing

**Comment by hsloot** [comment]
- The section on *how to contribute* in the file `REAMDE.Rmd` should reference the `CONTRIBUTING.md` document and outline the most important points.
- It should mention *documentation*, *testing*, *providing benchmarks*, and using `lintr`.
