### ISSUE TITLE
Scientific documentation

### ISSUE THREAD

**Issue by hsloot** [hsloot/rmo#4]
### Feature request: Scientific documentation of Marshall-Olkin distributions

For a good collaboration, the background material must be accessible to all possible collaborators. 

### To-Do's

- [x] Create a document for background information

Write a section on

- [x] the classical definition of Marshall-Olkin distributions
- [x] the exogenous shock model
- [x] the Arnold model
- [x] operations on Marshall-Olkin distributions
- [x] the exchangeable Marshall-Olkin distribution
- [x] the modification of the Arnold model for exchangeable distributions
- [x] the extendible Marshall-Olkin distribution
- [x] the Cuadras-Augé distribution
- [x] Lévy frailty models
- [x] Models based on hierarchical building blocks

### References

Mai, J. F., & Scherer, M. (2017). Simulating Copulas.

**Comment by hsloot** [comment]
- the documentation should be an .Rmd document placed in the `vignettes` directory and be complient with the article format of the [`pkgdown`-package](https://pkgdown.r-lib.org/articles/pkgdown.html)
- everything should be as clear and consise as possible and omit any proofs and additional examples
