### ISSUE TITLE
[REFACTOR] cpp11 conversion

### ISSUE THREAD

**Issue by hsloot** [hsloot/rmo#63]
## Summary

Since we use a limited range of Rcpp's functionality, we might benefit from switching to cpp11 (see https://github.com/r-lib/cpp11). However, some of the currently exported functions and tests might not work and have to be changed. The main benefit would probably be reduced compilation time. 

## Proposal

- Create a branch, based on master, which uses cpp11 instead of Rcpp
- Needed changes in unit tests and exported functions such that the procedure described in https://cpp11.r-lib.org/articles/converting.html#mechanics-of-converting-a-package-from-rcpp work can be upstreamed to master. 

## TODO

- [ ] Create branch from master
- [ ] Refactor functions with in-out parameters
- [ ] Refactor functions with non-standard parameters (e.g. Nullable)
